### ISSUE TITLE
HDFS_train.log 

### ISSUE THREAD

**Issue by amitkamthane** [WraySmith/log-anomaly#14]
Not able find the data HDFS.log and HDFS_train.log mentioned over path 

https://github.com/WraySmith/log-anomaly/tree/main/parse
Please guide.

**Comment by WraySmith** [comment]
https://github.com/WraySmith/log-anomaly/blob/main/parse/raw_data.ipynb provides details

**Comment by the-yaz** [comment]
in this part :  subblocks_train = fe.fit_transform(
        events_train_values,
        term_weighting="tf-idf",
        length_percentile=95,
        window_size=16,
    ) .
 I got this error : ValueError: height and width must be > 0 .
And this is final shape will be  -1 14 , i don't know why size[0] = -1 .
I tried to modify height and width but it didn't  ,  can you help ?
