### ISSUE TITLE
 final shape will be -1 14

### ISSUE THREAD

**Issue by the-yaz** [WraySmith/log-anomaly#15]
in this part : subblocks_train = fe.fit_transform(
events_train_values,
term_weighting="tf-idf",
length_percentile=95,
window_size=16,
) .
I got this error : ValueError: height and width must be > 0 .
And this is final shape will be -1 14 , i don't know why size[0] = -1 .
I tried to modify height and width but it didn't , can you help ?
I found out that it's self.nums_rows is the one = -1 but when i tried to change it  i got this error 
ValueError: window shape cannot be larger than input array shape.
UPDATE : the max seq length :  14 and windows size is 16 , so self.num_rows = self.max_seq_length - self.window_size + 1 gonna equal -1 and even when i change for exemple Windows to 14 or add like 3 it still got erreur of window ssshape 
can you help me ?

**Comment by WraySmith** [comment]
Hi, it's been quite a while since I've looked at this code at this point (around 2 years at this point). Others have run into problems running the code and it's typically has been due to not following the instructions for setting up the data or following the process. I'm not saying that's the case here but it's the first question I'll start with - have all of the instructions been followed and are you following the process in the notebooks and getting the same output that is shown in the notebooks? If not, I can try and debug at a very high level.

**Comment by the-yaz** [comment]
First thanks for the reply , I followed the instructions in github and I even check your website for more information , Second I spend few hours trying to fix it and foundout the problem was that the window_size in project_processor was 16 while in sliding_window_process specially in fit_transform window_size was only 14 , I made them both 14 and it's worked . I have a question if you don't mind ,I knows CNN is a supervised algorithm , so if I want to test other type of logs I should create an exemple of anomalies in this log like you did in anomaly_label ? Thanks again for your response and thanks for sharing this project .

**Comment by WraySmith** [comment]
Glad to hear you sorted it out. If you're going to to try and use other logs then yes, you would need to structure the input the same as the first step in the parsing step (see the example_data folder) and then use drain to parse the logs. To be honest, it likely won't be that easy unless you already have labelled log files as anomalous or not anomalous. This first step is more relevant to log parsing and less into the repos approach (ie can you parse your logs and then have a supervised dataset).

**Comment by chethanrraj90** [comment]
Please provide the website link or provide the instructions to run this project I would be grateful 
Please help

**Comment by WraySmith** [comment]
the instructions are embedded throughout the READMEs and notebooks in the project
